name: Samples - Event Sourcing with Spring Boot and EventStoreDB

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
    paths:
      - "samples/event-sourcing-esdb-simple/**"
  # run it during pull request
  pull_request:
    paths:
      - "samples/event-sourcing-esdb-simple/**"

defaults:
  run:
    working-directory: samples/event-sourcing-esdb-simple

jobs:
  build-and-test-code:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      # define the test matrix
      matrix:
        java-version: [17, 18]

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose up -d

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "adopt"
          cache: gradle

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-version: wrapper
          build-root-directory: samples/event-sourcing-esdb-simple

      - name: Archive test report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test report
          path: ./samples/event-sourcing-esdb-simple/build/test-results/test

      - name: Stop containers
        if: always()
        run: docker-compose down
