name: Workshop - Introduction to Event Sourcing - Solved

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
    paths:
      - "workshops/introduction-to-event-sourcing/solved/**"
  # run it during pull request
  pull_request:
    paths:
      - "workshops/introduction-to-event-sourcing/solved/**"

defaults:
  run:
    working-directory: workshops/introduction-to-event-sourcing/solved

jobs:
  build-and-test-code:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose up -d

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"
          cache: gradle

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-version: wrapper
          build-root-directory: workshops/introduction-to-event-sourcing/solved

      - name: Archive test report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test report
          path: ./workshops/introduction-to-event-sourcing/solved/build/test-results/test

      - name: Stop containers
        if: always()
        run: docker-compose down
